name             'sidekiq'
maintainer       'Maxence Decrosse'
maintainer_email 'maxence@spotistic.com'
license          'All rights reserved'
description      'Runs sidekiq'
version          '0.0.1'
